---
- name: Get IP address of a host
  hosts: all
  gather_facts: yes
  become: yes
  
  tasks:
  - name: Display IP address
    ansible.builtin.debug:
      msg: "{{ ansible_default_ipv4.address }}"
      #msg: "{{ ansible_distribution }}"
