---
- name: installing Apache Service
  hosts: all
  become: yes

  tasks:
  - name: installing apache service software
    ansible.builtin.yum:
      name: httpd
      state: latest

  - name: activating apache service
    ansible.builtin.service:
      name: httpd
      state: started
      enabled: yes 

      
  - name: Copy using inline content
    ansible.builtin.copy:
      content: 'Novo teste do Apache para Adiq http serviço'
      dest: /var/www/html/index.html
