---
- name: Zabbix teste with Kabana
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 8001
  rules:
    - name: debug
      condition: event.payload is defined
      action:
        debug:
        #run_job_template:
        #  name: test_ping_1
        #  organization: Org_Producao

