---
- name: Zabbix teste with Kabana
  hosts: all
  become: yes
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5001
  rules:
    - name: debug
      condition: event.payload is defined
      action:
        debug:
          msg: "teste deu certo"
        #run_job_template:
        #  name: test_ping_1
        #  organization: Org_Producao

